server:
  port: ${APP_PORT:8080}

spring:
  application.name: ${APP_NAME:api}
  profiles:
    active: ${ACTIVE_PROFILES:local}
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:confa}?serverZoneId=Europe/Moscow
    username: ${DB_USERNAME:confa}
    password: ${DB_PASSWORD:confa}
    pool:
      enabled: true
      initial-size: 2
      max-size: 2
      max-life-time: 10m
      validation-query: select 1
      validation-depth: remote


security:
  password-encoder:
    secret: ${PASSWORD_ENCODER_SECRET:fsdcgscdrwrcdxgfscdfdscdgfcgw}
  jwt:
    auth-secret: ${JWT_SECRET:vjxkcjvkfldvkdfjvjdfnvjkdjshdnksjdv}
    access-expiration: ${JWT_ACCESS_EXPIRATION:PT10M}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:PT12H}
    issuer: ${spring.application.name}

livekit:
  host: ${LIVEKIT_URL:https://live.confa.space}
  apiKey: ${LIVEKIT_API_KEY:yourapikey}
  apiSecret: ${LIVEKIT_API_SECRET:yourapisecret}
  defaultRoom: demo